name: Daily Remote Job Alert

on:
  schedule:
    - cron: '0 9 * * *'   # 9:00 UTC = 10:00 Nigeria time
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run job scraper
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python job_scraper.py
